package com.bigprime.source.spi.constant;

/**
 * @author lyw
 * @version 1.0
 */
public enum DdlStatementType {
    GET_DB_STATEMENT,
    GET_TABLE_STATEMENT,
    GET_COLUMN_STATEMENT,
    GET_INDEX_STATEMENT,
    GET_VIEW_STATEMENT,
    GET_FUNCTION_STATEMENT,
    CREATE_TABLE_STATEMENT,
    CREATE_COLUMN_STATEMENT,
    CREATE_INDEX_STATEMENT,
    CREATE_VIEW_STATEMENT,
    CREATE_FUNCTION_STATEMENT,
    ALTER_TABLE_STATEMENT,
    ALTER_COLUMN_STATEMENT,
    ALTER_INDEX_STATEMENT,
    ALTER_VIEW_STATEMENT,
    ALTER_FUNCTION_STATEMENT,
    DROP_TABLE_STATEMENT,
    DROP_COLUMN_STATEMENT,
    DROP_INDEX_STATEMENT,
    DROP_VIEW_STATEMENT,
    DROP_FUNCTION_STATEMENT,
    SHOW_CREATE_TABLE_STATEMENT,
}
